import React, { useState, useEffect } from 'react';
import { X, MessageCircle, Upload, File, Trash2, Send, AlertCircle, Info, HelpCircle } from 'lucide-react';
import { SupportTicket } from '../types';

export interface ContactSupportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (ticket: Omit<SupportTicket, 'id' | 'status' | 'createdAt' | 'updatedAt'>) => void;
  // Context for auto-filling
  userEmail?: string;
  userRole?: 'buyer' | 'seller';
  userId?: string;
  userName?: string; // User's display name
  context?: {
    type: 'booking' | 'order' | 'listing' | 'general';
    bookingId?: string;
    orderId?: string;
    listingId?: string;
    listingName?: string;
  };
  onNavigate?: (page: string) => void;
}

const SUPPORT_CATEGORIES = [
  'Booking/Order Issues',
  'Payment Problems',
  'Account Issues',
  'Technical Support',
  'Refund Request',
  'Service/Product Quality',
  'Delivery/Shipping Issues',
  'Other'
];

export function ContactSupportModal({
  isOpen,
  onClose,
  onSubmit,
  userEmail: initialEmail,
  userRole = 'buyer',
  userId,
  userName,
  context,
  onNavigate
}: ContactSupportModalProps) {
  const [email, setEmail] = useState(initialEmail || '');
  const [subject, setSubject] = useState('');
  const [category, setCategory] = useState('');
  const [message, setMessage] = useState('');
  const [attachments, setAttachments] = useState<File[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  
  // Determine if user is logged in (has userId)
  const isLoggedIn = !!userId;
  
  // Determine if fields should be disabled (auto-generated)
  const isSubjectAutoGenerated = !!context && (context.type !== 'general' || (context.bookingId || context.orderId || context.listingName));

  // Auto-generate subject based on context
  useEffect(() => {
    if (context && !subject) {
      let generatedSubject = '';
      
      if (context.type === 'booking' && context.bookingId && context.listingName) {
        generatedSubject = `${context.listingName} - Booking #${context.bookingId}`;
      } else if (context.type === 'order' && context.orderId && context.listingName) {
        generatedSubject = `${context.listingName} - Order #${context.orderId}`;
      } else if (context.type === 'listing' && context.listingName) {
        generatedSubject = `${context.listingName} - Inquiry`;
      } else if (context.type === 'general') {
        generatedSubject = 'Support Request';
      }
      
      if (generatedSubject) {
        setSubject(generatedSubject);
      }
    }
  }, [context, subject]);

  // Auto-fill email if user is logged in (for display purposes, but we'll use userId)
  useEffect(() => {
    if (initialEmail && !email && !isLoggedIn) {
      setEmail(initialEmail);
    }
  }, [initialEmail, email, isLoggedIn]);

  if (!isOpen) return null;

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      const newFiles = Array.from(files).filter(file => {
        // Allow PDF, images, and common document types
        const allowedTypes = [
          'application/pdf',
          'image/jpeg',
          'image/jpg',
          'image/png',
          'image/gif',
          'image/webp',
          'application/msword',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        ];
        return allowedTypes.includes(file.type) && file.size <= 10 * 1024 * 1024; // 10MB limit
      });
      
      setAttachments(prev => [...prev, ...newFiles].slice(0, 5)); // Max 5 files
    }
  };

  const removeAttachment = (index: number) => {
    setAttachments(prev => prev.filter((_, i) => i !== index));
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    // If not logged in, validate email
    if (!isLoggedIn) {
      if (!email.trim()) {
        newErrors.email = 'Email is required';
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        newErrors.email = 'Please enter a valid email address';
      }
    }

    if (!subject.trim()) {
      newErrors.subject = 'Subject is required';
    }

    if (!category) {
      newErrors.category = 'Please select a category';
    }

    if (!message.trim()) {
      newErrors.message = 'Message is required';
    } else if (message.trim().length < 10) {
      newErrors.message = 'Message must be at least 10 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);

    try {
      const ticketData: Omit<SupportTicket, 'id' | 'status' | 'createdAt' | 'updatedAt'> = {
        userId: isLoggedIn ? userId : undefined, // Only include userId if logged in
        userEmail: isLoggedIn ? (initialEmail || '') : email.trim(), // Use email from user if logged in, otherwise from form
        userRole,
        subject: subject.trim(),
        category,
        message: message.trim(),
        attachments,
        context: context || { type: 'general' }
      };

      await onSubmit(ticketData);

      // Reset form
      setEmail(isLoggedIn ? (initialEmail || '') : '');
      setSubject('');
      setCategory('');
      setMessage('');
      setAttachments([]);
      setErrors({});
      
      onClose();
    } catch (error) {
      console.error('Error submitting support ticket:', error);
      setErrors({ submit: 'Failed to submit ticket. Please try again.' });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClose = () => {
    if (!isSubmitting) {
      setEmail(isLoggedIn ? (initialEmail || '') : '');
      setSubject('');
      setCategory('');
      setMessage('');
      setAttachments([]);
      setErrors({});
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-[#FFFFFF] rounded-xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="bg-[#3D1560] text-white p-4 rounded-t-xl flex justify-between items-center sticky top-0 z-10">
          <div className="flex items-center gap-3">
            <MessageCircle className="w-6 h-6" />
            <h2 className="text-xl font-semibold">Contact Support</h2>
          </div>
          <button
            onClick={handleClose}
            disabled={isSubmitting}
            className="text-white hover:text-[#CDCED8] transition-colors disabled:opacity-50"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          {/* From (UserId if logged in, Email if not) */}
          <div>
            <label className="block text-sm font-medium text-[#383A47] mb-2">
              From <span className="text-[#DF678C]">*</span>
            </label>
            {isLoggedIn ? (
              // Logged in: Show User ID (read-only)
              <div className="w-full px-4 py-2.5 border border-[#CDCED8] rounded-lg bg-[#F8F8FA]">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-mono text-[#383A47]">{userId}</p>
                  <div className="px-2 py-1 bg-[#E8F5E9] rounded text-xs font-medium text-[#4CAF50]">
                    Logged in
                  </div>
                </div>
              </div>
            ) : (
              // Not logged in: Show email input
              <div>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#3D1560] focus:border-[#3D1560] transition-all bg-white ${
                    errors.email ? 'border-[#DF678C]' : 'border-[#CDCED8]'
                  }`}
                  placeholder="your.email@example.com"
                />
                {errors.email && (
                  <p className="text-sm text-[#DF678C] mt-1 flex items-center gap-1">
                    <AlertCircle className="w-4 h-4" />
                    {errors.email}
                  </p>
                )}
              </div>
            )}
          </div>

          {/* Subject */}
          <div>
            <label className="block text-sm font-medium text-[#383A47] mb-2">
              Subject <span className="text-[#DF678C]">*</span>
            </label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#3D1560] focus:border-[#3D1560] transition-all ${
                errors.subject ? 'border-[#DF678C]' : 'border-[#CDCED8]'
              } ${isSubjectAutoGenerated ? 'bg-[#F8F8FA] cursor-not-allowed' : 'bg-white'}`}
              placeholder="Brief description of your issue"
              disabled={isSubjectAutoGenerated}
              readOnly={isSubjectAutoGenerated}
            />
            {errors.subject && (
              <p className="text-sm text-[#DF678C] mt-1 flex items-center gap-1">
                <AlertCircle className="w-4 h-4" />
                {errors.subject}
              </p>
            )}
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-[#383A47] mb-2">
              Category <span className="text-[#DF678C]">*</span>
            </label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#3D1560] focus:border-[#3D1560] transition-all bg-white ${
                errors.category ? 'border-[#DF678C]' : 'border-[#CDCED8]'
              }`}
            >
              <option value="">Select a category</option>
              {SUPPORT_CATEGORIES.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
            {errors.category && (
              <p className="text-sm text-[#DF678C] mt-1 flex items-center gap-1">
                <AlertCircle className="w-4 h-4" />
                {errors.category}
              </p>
            )}
          </div>

          {/* Message */}
          <div>
            <label className="block text-sm font-medium text-[#383A47] mb-2">
              Message <span className="text-[#DF678C]">*</span>
            </label>
            <div className="space-y-1">
              <textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={6}
                className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#3D1560] focus:border-[#3D1560] transition-all resize-none bg-white ${
                  errors.message ? 'border-[#DF678C]' : 'border-[#CDCED8]'
                }`}
                placeholder="Please describe your issue in detail. Include any relevant information that will help us assist you better..."
              />
              <div className="flex items-center justify-between">
                <p className="text-xs text-[#70727F]">
                  {message.length > 0 ? (
                    <span className={message.length < 10 ? 'text-[#DF678C]' : 'text-[#4CAF50]'}>
                      {message.length} / 10 characters minimum
                    </span>
                  ) : (
                    'Minimum 10 characters required'
                  )}
                </p>
                {message.length > 500 && (
                  <p className="text-xs text-[#70727F]">
                    {message.length} characters
                  </p>
                )}
              </div>
            </div>
            {errors.message && (
              <p className="text-sm text-[#DF678C] mt-1 flex items-center gap-1">
                <AlertCircle className="w-4 h-4" />
                {errors.message}
              </p>
            )}
          </div>

          {/* Attachments */}
          <div>
            <label className="block text-sm font-medium text-[#383A47] mb-2">
              Attachments (Optional)
            </label>
            {attachments.length > 0 && (
              <div className="mb-3 space-y-2">
                {attachments.map((file, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between p-3 bg-[#F8F8FA] rounded-lg border border-[#E8E9ED] hover:border-[#CDCED8] transition-colors"
                  >
                    <div className="flex items-center gap-3 flex-1 min-w-0">
                      <div className="flex-shrink-0">
                        <File className="w-5 h-5 text-[#3D1560]" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-[#383A47] truncate">{file.name}</p>
                        <p className="text-xs text-[#70727F]">{formatFileSize(file.size)}</p>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => removeAttachment(index)}
                      className="flex-shrink-0 text-[#DF678C] hover:text-[#D84773] transition-colors p-1 rounded hover:bg-[#FFE5ED]"
                      aria-label="Remove attachment"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            )}
            {attachments.length < 5 && (
              <label className="cursor-pointer">
                <input
                  type="file"
                  multiple
                  accept=".pdf,.jpg,.jpeg,.png,.gif,.webp,.doc,.docx"
                  onChange={handleFileUpload}
                  className="hidden"
                />
                <div className="border-2 border-dashed border-[#CDCED8] rounded-lg p-3 text-center hover:border-[#3D1560] hover:bg-[#F8F8FA] transition-all group">
                  <Upload className="w-5 h-5 text-[#70727F] mx-auto mb-1.5 group-hover:text-[#3D1560] transition-colors" />
                  <p className="text-xs text-[#383A47] font-medium mb-0.5">
                    Click to upload files
                  </p>
                  <p className="text-xs text-[#70727F]">
                    PDF, Images, DOC up to 10MB ({attachments.length}/5)
                  </p>
                </div>
              </label>
            )}
          </div>

          {/* Submit Error */}
          {errors.submit && (
            <div className="p-3 bg-[#FFE5ED] border border-[#DF678C] rounded-lg flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-[#DF678C]" />
              <p className="text-sm text-[#DF678C]">{errors.submit}</p>
            </div>
          )}

          {/* Help Center Link */}
          {onNavigate && (
            <div className="pt-2 border-t border-[#E8E9ED]">
              <button
                type="button"
                onClick={() => {
                  onClose();
                  onNavigate(userRole === 'seller' ? 'help?seller' : 'help');
                }}
                className="w-full flex items-center justify-center gap-2 text-sm text-[#3D1560] hover:text-[#6D26AB] transition-colors py-2"
              >
                <HelpCircle className="w-4 h-4" />
                <span>Check Help Center for answers</span>
              </button>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-[#E8E9ED]">
            <button
              type="button"
              onClick={handleClose}
              disabled={isSubmitting}
              className="flex-1 px-4 py-3 border border-[#CDCED8] text-[#383A47] rounded-lg hover:bg-[#F8F8FA] hover:border-[#CDCED8] transition-colors disabled:opacity-50 font-medium"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting || !category || !message.trim() || (!isLoggedIn && !email.trim())}
              className="flex-1 px-4 py-3 bg-[#3D1560] text-white rounded-lg hover:bg-[#6D26AB] disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-semibold flex items-center justify-center gap-2 shadow-sm hover:shadow-md"
            >
              {isSubmitting ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Submitting...
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  Submit
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
